public class Fibonacci {

    public static void main(String[] args) {

/*  Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
*   By starting with 1 and 2, the first 10 terms will be:
*  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/     
        
        List<Integer> fiboList = new ArrayList<>();
        int evenNumSum = 0;
        for (int i = 1; i < 50; i++) {

            if (i < 4) {

                fiboList.add(i);

                System.out.println(i);
                System.out.print(",");

            } else {

                int numOne = fiboList.get(i - 3);
                int numTwo = fiboList.get(i - 2);

                int numSum = numOne + numTwo;
                System.out.println(numSum);
                System.out.print(",");
                fiboList.add(numSum);
            }
        }

        for (Integer num : fiboList) {
            if (num <= 4000000 && num % 2 == 0) {
                evenNumSum = evenNumSum + num;
            }

        }
        System.out.println("");
        System.out.println("Sum of only even values not greater than 4000000:" + evenNumSum);

    }

}
